from nanosense.core.database_manager import DatabaseManager


def test_save_spectrum_links_batch_item(tmp_path):
    db_path = tmp_path / "demo_batch.db"
    manager = DatabaseManager(str(db_path))
    try:
        project_id = manager.find_or_create_project("Protein Screening", "demo data")
        assert project_id is not None

        run_id = manager.create_batch_run(
            project_id,
            "Demo Batch Run",
            layout_reference="demo-layout",
            operator="tester",
            notes="autogenerated for unit test",
        )
        assert run_id is not None

        item_map = manager.create_batch_items(
            run_id,
            {
                "A1": {"sample": "Alpha"},
            },
        )
        assert "A1" in item_map
        item_id = item_map["A1"]

        exp_id = manager.create_experiment(
            project_id,
            "Run A1",
            "Batch Measurement",
            "2025-01-01 00:00:00",
            operator="tester",
        )
        assert exp_id is not None

        manager.attach_experiment_to_batch_item(item_id, exp_id)

        manager.save_spectrum(
            exp_id,
            "Signal",
            "2025-01-01 00:00:00",
            [500.0, 501.0],
            [1.0, 1.1],
            batch_run_item_id=item_id,
        )

        cursor = manager.conn.execute(
            "SELECT batch_run_item_id FROM spectrum_sets WHERE experiment_id = ?",
            (exp_id,),
        )
        row = cursor.fetchone()
        assert row is not None
        assert row[0] == item_id
    finally:
        manager.close()
